version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: dennisoliveira/joomla15
    container_name: joomla15-web
    tty: true
    volumes:
      - ./www:/var/www
    networks:
      default:
        ipv4_address: ${WEB_IP}

  db:
    image: mysql:5.5.40
    container_name: joomla15-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=joomla
    networks:
      default:
        ipv4_address: ${MYSQL_IP}

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: ${NETWORK_CONFIG_SUBNET}